# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-25 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_texttest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='texttest',
            field=models.TextField(default='this is just a test'),
        ),
    ]
